Se agrega ancla para acceder directamente a las donaciones
devschile/devschile.cl pull request #24
Opened 2019-10-24 23:32 UTC by lgaticaq

Esto con el fin de agregar un enlace directo a las donaciones desde distintas partes. Por ejemplo desde el script [como-donar.js](https://github.com/devschile/huemul/blob/master/scripts/como-donar.js)

2019-10-24 23:35 UTC, lgaticaq commented
Ejemplo del ancla https://deploy-preview-24--distracted-noether-4e52ec.netlify.com/#donations

2019-10-25 02:13 UTC, juanbrujo approved these changes

2020-09-27 22:56 UTC, juanbrujo requested changes
El sitio se ha actualizado, puedes actualizar este PR para mergearlo? grax.

2020-09-27 23:42 UTC, lgaticaq commented
listeilor @juanbrujo, el deploy preview con el ancla en https://5f712359a282012ac1b1e547--distracted-noether-4e52ec.netlify.app/#donations

2020-09-28 00:29 UTC, juanbrujo approved these changes

2020-09-28 00:30 UTC, merged